### PR TITLE
Remove the entire api folder

### PR DESCRIPTION
**Pull request by paul-antal**
That's pretty much it... everything burned

### CODE REVIEW

**Comment by RaduCStefanescu** [comment]
Thanks for the PR @paul-antal 
Before we merge it, I want to make sure we have everything moved in the `monitorizare-vot` repo.

Currently, I know there is still the `Statistics` feature that was not yet moved.

**Comment by idormenco** [comment]
@RaduCStefanescu i think statistics was moved to api so this PR can be merged

**Comment by aniri** [comment]
@bvizureanu can you please check if it is safe to do this? :smile:

**Comment by aniri** [comment]
I think we can close this as it was done again in https://github.com/code4romania/monitorizare-vot-ong/pull/229

**Pull request closed without merging**
