### PR TITLE
Feature/284 new ui statics page

### LINKED ISSUE #284: [Stats] Update statistics page to new UI
Adapt the UI for the statistics page to make it as similar as possible to the one here https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0 under Reports. 

Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent.

Also, make sure all texts are extracted in translation files. 

Screenshot from 2020-10-13 11-28-18

Screenshot from 2020-10-13 11-12-57

### PR DESCRIPTION
**Pull request by Botosio**
### What does it fix?

New Reports/Statistics UI Completed with Detail now in a dialog.  Paginator removed(!)
Closes #284

### How has it been tested?

UI, and responsive design tested.
image
image

### CODE REVIEW

**Comment by Botosio** [comment]
@aniri please review the statistics-details.component.ts page.  I removed.... a lot.

**Comment by aniri** [comment]
@Botosio woooh! nice code cleanup!! :rocket: Could you also update the card titles as they are now made up of header + subheader and they should just be one line of text? The texts for them should also be translatable. It would be great if you could also include this change, but it's just a nice-to-have. Please ignore this if it's too much of a hassle and I'll add a separate issue for this :)

**Review by aniri — APPROVED** [review]

**Comment by aniri** [comment]
I'll open a new issue for the mentioned updates ;)

**Comment by Botosio** [comment]
@aniri hey sorry I missed your message, work started to pick up over here.  Just assigned to me and I can fix, seems pretty simple.

**Comment by aniri** [comment]
> @aniri hey sorry I missed your message, work started to pick up over here. Just assigned to me and I can fix, seems pretty simple.

@Botosio no problem ;) I'll assign the new task to you, if you have the time! Thanks!

**Pull request merged**
