### PR TITLE
Updated login to new UI

### LINKED ISSUE #233: [UI] Update login screen to new UI
The new UI can be found here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

### PR DESCRIPTION
**Pull request by Botosio**
### What does it fix?

[UI] Update login screen to new UI

The new UI can be found here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

Closes #233

### How has it been tested?
No functionality changed, just UI.

image

### CODE REVIEW

**Comment by Botosio** [comment]
I think I need a new logo image, which is the one in the global header.

Also updated the Body background, let me know if you are not ready to change this.  Every mockup had it like this, not sure how the other areas will look.

**Comment by aniri** [comment]
@Botosio would this do?

Bitmap

I managed to find a bigger image :smiley:

**Comment by Botosio** [comment]
> @Botosio would this do?
> 
> Bitmap
> 
> I managed to find a bigger image 😃

I don't think the background is transparent.  So the yellow won't come through.
image

**Comment by Botosio** [comment]
@aniri 
image
 thoughts?

**Comment by aniri** [comment]
logo_new

@Botosio this one should be transparent :D

**Comment by Botosio** [comment]
@aniri updated
image

**Comment by aniri** [comment]
@Botosio OMG it looks awesome! thank youuuuu!!! :smiley:

**Review by aniri — APPROVED** [review]

**Pull request merged**
