### PR TITLE
updated form spacing and mobile

### LINKED ISSUE #279: [Forms] Adjust padding and test responsiveness of the add form screen on smaller devices

### PR DESCRIPTION
**Pull request by Botosio**
### What does it fix?
Fixed padding and responsive design on the forms page

Closes #279

### How has it been tested?

Tested by using the browser device toolbar and testing with iPad and iPad pro layout. (lg to md for bootstrap).

image

mobile
image

### CODE REVIEW

**Comment by Botosio** [comment]
@aniri submitted

**Comment by aniri** [comment]
hmmm, they got aligned weirdly on my screen:

Screenshot from 2020-10-16 19-35-52

It's not a really big issue though and I guess it will be fixed here: https://github.com/code4romania/monitorizare-vot-ong/issues/280

**Comment by Botosio** [comment]
> hmmm, they got aligned weirdly on my screen:
> 
> Screenshot from 2020-10-16 19-35-52
> 
> It's not a really big issue though and I guess it will be fixed here: #280

Oh it's the mt-4-md class. I need to remove it. give me a min and I can fix

**Comment by Botosio** [comment]
@aniri updated

**Review by aniri — APPROVED** [review]

**Pull request merged**
