### PR TITLE
Fix: hamburger on smaller screens

### LINKED ISSUE #275: [Bug] Hamburger menu not working on smaller screens

### PR DESCRIPTION
**Pull request by Andrei0872**
### What does it fix?

Closes #275 

It was a problem with jquery3.5.0, as discovered in this [SO thread](https://stackoverflow.com/questions/61177140/uncaught-typeerror-cannot-convert-object-to-primitive-valuezone-evergreen-js1).

The solution was to update jquery: 

```bash
yarn upgrade --latest jquery
```

### CODE REVIEW

**Comment by jrstrayhorn** [comment]
Hello @Andrei0872 - a suggestion on this item, since we're using Angular and ng-bootstrap we shouldn't need to use jQuery.  Here is an example of getting the hamburger menu working with ngbCollapse directive in ng-bootstrap

https://ng-bootstrap.github.io/#/components/collapse/examples

Hopefully this help! 😊

**Comment by Andrei0872** [comment]
Hello @jrstrayhorn , I thought it only had to be fixed, it also didn't mention an alternative to jquery.

I also think that replacing it right now will come with a cost.

**Comment by jrstrayhorn** [comment]
@Andrei0872 - I think you are working from an older version of develop branch.  The latest version of develop branch no longer has jquery as a dependency in the package.json file but it does have ng-bootstrap.

https://github.com/code4romania/monitorizare-vot-ong/blob/develop/package.json

**Comment by Andrei0872** [comment]
@jrstrayhorn  I think it's because I branched off from "master", as it is mentioned in "CONTRIBUTING.MD". So it guess it should've been the "develop" branch, right?

I will amend it tomorrow. Thank you

**Comment by aniri** [comment]
> @jrstrayhorn I think it's because I branched off from "master", as it is mentioned in "WORKFLOW.MD". So it guess it should've been the "develop" branch, right?
> 
> I will amend it tomorrow. Thank you

@Andrei0872 sorry for the confusion, I have updated the workflow docs :smiley:

**Comment by Andrei0872** [comment]
No worries! I think I should close this PR then, if that's ok.

**Pull request closed without merging**
