### PR TITLE
#60 Forms is still work in progress

### PR DESCRIPTION
**Pull request by tbgdn**
Form sets and form sections can be added or deleted based on a mocked
API that stores data in json files.
Questions can be only viewed and the edit part is the work in progress.
To avoid the existing functionality for answers and emergencies, I chose
to create a new model, namely EditableForms. Once the edit part is done,
I plan to merge the existing Forms model into a single one.

### CODE REVIEW

**Comment by mihaisavezi** [comment]
Can we make commits slightly more atomic ? E.g. for what I mean by more [atomic](http://www.pauline-vos.nl/atomic-commits/).

It's easier for the reviewer to follow the changes.

**Comment by tbgdn** [comment]
> Can we make commits slightly more atomic ? E.g. for what I mean by more [atomic](http://www.pauline-vos.nl/atomic-commits/).
> 
> It's easier for the reviewer to follow the changes.
Sorry for this big commit and thanks for the tips link. If this is way too annoying I can break it into smaller commits. Just let me know.

**Comment by mihaisavezi** [comment]
Yes, please, going forward. It will speed up the review process.

**Comment by tbgdn** [comment]
Closing this and opening a new PR with smaller commits.

**Pull request closed without merging**
