### PR TITLE
Feature/268 update form view to new ui

### LINKED ISSUE #268: [Forms] Update form view to new UI
Please see the new UI here under Create form: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1120%3A31

### PR DESCRIPTION
**Pull request by Botosio**
### What does it fix?
Updated form view to new UI
Based off this mockup: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1120%3A31
Closes #268 

Changes to CSS, the color of buttons, margins around elements

### How has it been tested?
Ran locally, took a screenshot.  No functional change.

image

### CODE REVIEW

**Comment by aniri** [comment]
Hey @Botosio . It is looking great, thank you :rocket: 

Just a few more ideas (if you have the time):
- could you add the description text-areas for forms and form sections? They are in the design but were missed in the initial implementation.
- could you check that all labels and dropdown values etc are extracted as texts in the translation files? The question type downdown values should also show text labels instead of the enum values (multiple choice, single choice, single choice with free text option, multiple choice with free text option). You can use english both in the en file and the ro translations. We'll check them later and translate them.

Thanks!

**Review by Utwo — DISMISSED** [review]

**Comment by Utwo** [comment]
:100: nice and clean!

**Comment by Botosio** [comment]
@aniri sure no problem.

**Comment by Botosio** [comment]
@aniri There is a checkbox on the edit form, do you still want this?  It isn't in the design?

**Comment by aniri** [comment]
> @aniri There is a checkbox on the edit form, do you still want this? It isn't in the design?

@Botosio Yes, we do need the checkbox. Thanks!

**Comment by Botosio** [comment]
Ok Updated Screenshot, I think I have all the translations and the added description, @aniri 
image

**Review by aniri — APPROVED** [review]

**Pull request merged**
