### PR TITLE
[Forms] Add delete confirmation when deleting forms #264

### LINKED ISSUE #264: [Forms] Add delete confirmation when deleting forms
Add a confirmation popup when pressing the delete option for a form in the forms list.

### PR DESCRIPTION
**Pull request by PushpikaWan**
### What does it fix?

Closes #264

### How has it been tested?
I couldn't login to the application therefore tried out bypassing login to other component

### CODE REVIEW

**Comment by aniri** [comment]
hi @PushpikaWan and thanks for your contribution! I think you missed placing a confirmation popup on forms:
Screenshot from 2020-10-07 14-39-25
Can you please check?

**Comment by PushpikaWan** [comment]
sure @aniri can u please provide user name and password for the testing.  Otherwise, I cannot log in into the system and I only test with one mock window... or Is there any other way to sign up

**Comment by aniri** [comment]
> sure @aniri can u please provide user name and password for the testing. Otherwise, I cannot log in into the system and I only test with one mock window... or Is there any other way to sign up

@PushpikaWan yes, you can use test / test2020 to login ;)

**Comment by PushpikaWan** [comment]
@aniri I added delete modal for other delete actions and I didn't get this place you want :) check now

**Review by Utwo — CHANGES_REQUESTED** [review]
After removing the .spec.ts file, this can be merged. Thank you for the contribution! :100:

**Comment by aniri** [comment]
@PushpikaWan thanks! It now works as expected :smiley: Could you please check the comment above and make a final small change to this PR so we can merge it?

**Comment by PushpikaWan** [comment]
@aniri, I did the requested changes. :)

**Review by aniri — APPROVED** [review]

**Pull request merged**
